### ISSUE TITLE
Version 1.14 installed on ubuntu-latest

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [hrishikesh-kadam/setup-lcov#1]
It seems that after running this in my workflow (for linux, mac and window) that the version installed on ubuntu-latest (ubuntu-22.04) is a very old version 1.14, without a new option (--erase-functions) I would like to use.

https://github.com/andrewdavidmackenzie/pigg/actions/runs/9522864197/job/26253268146?pr=159

while on macos it's 2.1-1 and much newer versions are available on ubuntu (https://launchpad.net/ubuntu/+source/lcov)

Does that sound correct?

Any way to get a newer version or lcov on ubuntu-latest?

**Comment by hrishikesh-kadam** [comment]
@andrewdavidmackenzie Noted.
I'll work on it next week.

**Comment by andrewdavidmackenzie** [comment]
I just checked. That is the latest version available on ubutu-latest/22.04, so it's really up to the Ubuntu/love maintainers to fix it.

You would have to build and install your own, newer, love package.
